### PR TITLE
add t0lte

### PR DESCRIPTION
**Pull request by 0xnth**
add t0lte

### CODE REVIEW

**Comment by akhilnarang** [comment]
@mrhainavn  none of us own it, would you like to maintain it?

**Comment by 0xnth** [comment]
@akhilnarang , yes. maybe. i want maintainer official for it.

**Comment by akhilnarang** [comment]
OK, will get to you, I'm busy with school, maybe in a week when we resume
dev I'll tell you

**Comment by 0xnth** [comment]
@akhilnarang, yes, i know. will wait untill you come back. Glad.
i have one ask : this rom has added "Logo OwnROM" on status bar yet?Thanks man

**Comment by akhilnarang** [comment]
Not yet, that will be one of the things I'm gonna add

**Comment by 0xnth** [comment]
Thanks sweet man. i think so.

**Pull request closed without merging**
