### PR TITLE
Remove wget module from magisk makefile

### PR DESCRIPTION
**Pull request by MZO9400**

### CODE REVIEW

**Comment by OwnDroid** [comment]
Why is this? @MZO9400

**Comment by OwnDroid** [comment]
Allready did this on my local repo

**Comment by MZO9400** [comment]
Because the wget is already being made in common, no need to make it again in zip dir

**Comment by MZO9400** [comment]
https://github.com/OwnROM/android_vendor_ownrom/blob/own-n/prebuilt/common/Android.mk

Multi definitions cause errors

**Comment by OwnDroid** [comment]
@MZO9400 as stated before, i allready did this at my local repo, will push later

**Comment by OwnDroid** [comment]
@MZO9400 but thanks btw

**Comment by MZO9400** [comment]
No worries :)

**Comment by MZO9400** [comment]
Okay so we're live lol, building... I'll be doing OP2 if you don't mind.

**Comment by OwnDroid** [comment]
@MZO9400 please contact me on Hangouts if you are interested in joining us...

mhrvisser21@gmail.com

**Pull request closed without merging**
